providers = ["node"]

[phases.setup]
nixPkgs = ["nodejs"]

[phases.install]
cmds = ["cd backend && npm install"]

[phases.build]
cmds = ["cd backend && npm run build"]

[start]
cmd = "cd backend && npx prisma generate && npm run start:prod"
